#! /bin/sh
### BEGIN INIT INFO
# Provides:          lxc
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts/stops linux containers
# Description:       Provides linux container management: start, stop or
#                    restart containers.
### END INIT INFO

# Author: Nigel McNie <nigel@mcnie.name>
#set -x

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="linux containers"
NAME=lxc
SCRIPTNAME=/etc/init.d/$NAME

. /lib/init/vars.sh
. /lib/lsb/init-functions


lxc_stopped_list=$(lxc-status | grep STOPPED | awk '{print $1}' | sed "s/'//g")
lxc_running_list=$(lxc-status | grep RUNNING | awk '{print $1}' | sed "s/'//g")
lxc_dir="/var/lib/lxc"

do_start()
{
  for C in $lxc_stopped_list ; do
    if [ -f $lxc_dir/$C/autostart ]; then
      log_progress_msg "$C"
      if lxc-info -n $C | grep STOPPED > /dev/null 2>&1; then
        screen -dm -S lxc-${C} /usr/bin/lxc-start -n $C
        lxc-wait -n $C -s RUNNING
        if [ $? -gt 0 ]; then
          return 2
        fi
      fi
    fi
  done
}

do_stop()
{
  for C in $lxc_running_list ; do
    log_progress_msg "$C"
    lxc-halt -q -n $C &
  done
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" #"$NAME"
	do_start
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC" #"$NAME"
	do_stop
	case "$?" in
		0|1) log_end_msg 0 ;;
		2) log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" #"$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
